---
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: root
permissions:
  - object: /home/ubuntu/www/scripts
    pattern: "*.sh"
    mode: 777
    type:
      - file
