steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$_BUCKET/app.yaml', 'app.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '/']
  timeout: 600s
# steps:
# #deploy step
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
#   timeout: 600s